/* Used to determine to play or not, default = play at preset times (always), play = play always, pause = don't play */
INSERT INTO `admin` VALUES
(1,'play');

/* Used to determine if default list is used*/
INSERT INTO `admin` VALUES
(2, 'false');

INSERT INTO `deflist` VALUES
(1, 'aalangatti mazha'),
(2, 'aaluma dolum'),
(3, 'aanandha yaazhai'),
(4, 'aathichoodi vijay antony'),
(5, 'aetho saigirai'),
(6, 'ale ale'),
(7, 'allah ninaithale inikkum'),
(8, 'amali thumali'),
(9, 'anargazhi kangalal kaithu sei'),
(10, 'anbe idhu rhythm'),
(11, 'anbil avan'),
(12, 'anjali anjali pushpanjali'),
(13, 'annakili 4 students'),
(14, 'arjunar villu gilli'),
(15, 'aruva meesai dhool'),
(16, 'athiradi karan sivaji'),
(17, 'ayyo pathikichu'),
(18, 'azhagiya laila'),
(19, 'chennai senthamizh'),
(20, 'chikkini chameli'),
(21, 'chinna chinna mazhai thuligal'),
(22, 'chinna chinnathai penne'),
(23, 'chudithar aninthu vantha sorgame'),
(24, 'dailamo dailamo'),
(25, 'devathaye vaa malaikottai'),
(26, 'dharshana hridayam'),
(27, 'dippam dappam'),
(28, 'dolu maachi deepavali'),
(29, 'en anbe sathyam'),
(30, 'en jannal nilavukku ennaachu'),
(31, 'en jannalil therivathu mozhi'),
(32, 'en kadhal solla'),
(33, 'en nanbane mangatha'),
(34, 'enge en punnagai'),
(35, 'ennamo edho ko'),
(36, 'enthan nenjil yesudhas'),
(37, 'feel my love kutty'),
(38, 'gulmuhar malare'),
(39, 'hey baby aegan'),
(40, 'hey baby raja rani'),
(41, 'hey keechu kiliye mugavari'),
(42, 'high on love'),
(43, 'i like you citizen'),
(44, 'idhu varai'),
(45, 'jeevamshamyi'),
(46, 'just the two of us'),
(47, 'kaala chashma'),
(48, 'kaatrin mozhi male'),
(49, 'kadhal mattum purivathillai'),
(50, 'kanaa kandaenadi'),
(51, 'kannai kasakkum sooriyano red'),
(52, 'kannal pesum penne'),
(53, 'kannamma ispade'),
(54, 'kannamma kaadhelennum'),
(55, 'kannan varum'),
(56, 'kannodu kanbathellam jeans'),
(57, 'kannum kannum nokia'),
(58, 'karu karu vizhigalal'),
(59, 'kodai kaala kaatre ilayaraja'),
(60, 'kunkuma nira sooryan'),
(61, 'kuruvi adicha music'),
(62, 'kutty pattas'),
(63, 'lajjavathiye'),
(64, 'life of ram'),
(65, 'machan peru madurey'),
(66, 'malai kaatru tamil pesutho'),
(67, 'malare mounama'),
(68, 'manase ila manase puthiya geethai'),
(69, 'manjal veyil'),
(70, 'mannippaaya'),
(71, 'mascara pottu'),
(72, 'mazhai nindra raman'),
(73, 'meesaya murukku title song'),
(74, 'mercury poove'),
(75, 'merke merke'),
(76, 'minsaram en meethu'),
(77, 'mudhal mazhai bheema'),
(78, 'mudhan mudalil paarthen hariharan aaha'),
(79, 'mudhar kanave'),
(80, 'mun paniya'),
(81, 'na na na mervin'),
(82, 'naattu koothu'),
(83, 'narumugaye'),
(84, 'nee himamazhayai'),
(85, 'nee kidaithai'),
(86, 'nee marlyn monroe'),
(87, 'nee otha sollu sollu'),
(88, 'nenje nenje ayan'),
(89, 'nenje nenje ratchagan'),
(90, 'nimirndhu nil saroja'),
(91, 'oh baby yaaradi nee mohiney'),
(92, 'oh nenje nenje mugavari'),
(93, 'oh oh sanam dasavatharam'),
(94, 'oru deivam thantha poove male'),
(95, 'oru paarvayil poo koduthai siva manasula sakthi'),
(96, 'oru vaarthai kekka iyya'),
(97, 'ottiyanam senju tharen variya'),
(98, 'oxygen lyric video kavan'),
(99, 'paartha mudhal naale'),
(100, 'paathagathi kannupattu'),
(101, 'paatu solli paada solli'),
(102, 'paatu thalaivan paadinal'),
(103, 'pachai kaatre abiyum naanum'),
(104, 'padichu paathen'),
(105, 'paravaye engu irukkirai'),
(106, 'parayuvan malayalam'),
(107, 'pazha muthir solai yesudhas'),
(108, 'po po yen sid sriram'),
(109, 'pogathe yuvan'),
(110, 'pon magal vanthal remix'),
(111, 'poosum manjal male'),
(112, 'poova poove poovellam kettupar'),
(113, 'poove sempoove'),
(114, 'poovukku poranthanalu little john'),
(115, 'ragasiyamai dum dum dum'),
(116, 'ragatulla'),
(117, 'roja poo aadivanthathu'),
(118, 'saayndhu saaynthu'),
(119, 'sada sada kavalan'),
(120, 'samajavaragamana'),
(121, 'sangeetha megam'),
(122, 'seval kozhi billa'),
(123, 'sevvaanam selai katti'),
(124, 'so baby doctor'),
(125, 'swasame thenali'),
(126, 'taj mahal oviya kadhal'),
(127, 'thaakuthe kan thaakuthe'),
(128, 'thani oruvan ninaithu vittal'),
(129, 'thanni karuthidichu'),
(130, 'thanthana thanthana thavasi'),
(131, 'thean thean thean kuruvi'),
(132, 'thirunelveli halwa da'),
(133, 'thodu thodu enave'),
(134, 'thom karuvil irunthom'),
(135, 'thozhiya en kadhaliya'),
(136, 'top tucker sarkar rahman tamil'),
(137, 'ulaga nayagane dasavatharam'),
(138, 'un paarvai mele pattal'),
(139, 'unakkena naan enakkena nee'),
(140, 'unakkul naane bombay jayashree'),
(141, 'unthan desathin'),
(142, 'uyirin uyire kaaka kaaka'),
(143, 'vaa vaa en devathaye aabiyum naanum'),
(144, 'vaadi pulla vaadi'),
(145, 'vaaji vaaji'),
(146, 'vachan vachan silambattam'),
(147, 'vaseegara'),
(148, 'verenna verenna vendum'),
(149, 'vikram title track'),
(150, 'vilambara idaivelai'),
(151, 'yaakai thiri'),
(152, 'yaar aval yaaro muppozhuthum un karpanaigal'),
(153, 'yaarodu yaaro yogi'),
(154, 'yeh nilave mugavari');
